QUESTION_MAP = {
  "q1_big_purchase_trim":{"prompt":"If a big purchase is coming, what do you trim first?",
    "options":{"subs":{"tags":{"frugality":1,"liquidity_pref":1},"scenarios":{"recession":0.4}},
               "eating":{"tags":{"frugality":1},"scenarios":{"recession":0.3}},
               "travel":{"tags":{"frugality":0.5},"scenarios":{"recession":0.2}},
               "nothing":{"tags":{"risk_tol":1},"scenarios":{}}}},
  "q2_booking_horizon":{"prompt":"How far in advance do you book travel?",
    "options":{"last_min":{"tags":{"planning_short":1},"scenarios":{"liquidity_stress":0.2}},
               "1_3m":{"tags":{},"scenarios":{}},
               "6_12m":{"tags":{"planning_long":1},"scenarios":{"recession":-0.2}}}},
  "q3_costs_up_10":{"prompt":"If fixed costs rose 10%, first reaction?",
    "options":{"negotiate":{"tags":{"adaptability":1},"scenarios":{"recession":-0.2}},
               "reduce_inv":{"tags":{"liquidity_pref":1},"scenarios":{"gilt_selloff":0.2}},
               "use_credit":{"tags":{"rate_sens":1},"scenarios":{"gilt_selloff":0.6}},
               "side_income":{"tags":{"resilience":1},"scenarios":{"recession":-0.2}}}},
  "q4_cash_buffer":{"prompt":"Preferred cash buffer?",
    "options":{"<1m":{"tags":{"liquidity_pref":-1,"risk_tol":1},"scenarios":{"reflation":0.2}},
               "3_6m":{"tags":{"liquidity_pref":1},"scenarios":{}},
               "12m":{"tags":{"liquidity_pref":2},"scenarios":{"recession":-0.2}}}},
  "q5_mortgage_reset":{"prompt":"If your fixed rate ended tomorrow, you'd…",
    "options":{"extend_term":{"tags":{"rate_sens":2},"scenarios":{"gilt_selloff":1.5}},
               "overpay":{"tags":{"property_caution":1,"liquidity_pref":1},"scenarios":{}},
               "switch_tracker":{"tags":{"rate_sens":1},"scenarios":{"gilt_selloff":1.0}},
               "do_nothing":{"tags":{"passive_bias":1},"scenarios":{}}}},
  "q6_windfall_5k":{"prompt":"First £5k of windfall goes to…",
    "options":{"mortgage":{"tags":{"property_caution":1},"scenarios":{}},
               "isa_equity":{"tags":{"risk_tol":1},"scenarios":{"reflation":0.3}},
               "premium_bonds":{"tags":{"liquidity_pref":1},"scenarios":{"gilt_selloff":0.2}},
               "home_improve":{"tags":{"property_conf":1},"scenarios":{}}}},
  "q7_home_value_check":{"prompt":"How often do you check your home’s value?",
    "options":{"rarely":{"tags":{"property_salience":-1},"scenarios":{}},
               "quarterly":{"tags":{"property_salience":1},"scenarios":{"property_crash":0.2}},
               "monthly":{"tags":{"property_salience":2},"scenarios":{"property_crash":0.4}}}},
  "q8_employer_freeze":{"prompt":"If your employer froze hiring and pay, you’d…",
    "options":{"upskill":{"tags":{"resilience":1},"scenarios":{"recession":-0.3}},
               "freelance":{"tags":{"resilience":1},"scenarios":{"recession":-0.2}},
               "cut_exp":{"tags":{"frugality":1},"scenarios":{"recession":-0.2}},
               "no_action":{"tags":{"risk_tol":1},"scenarios":{"recession":0.2}}}},
  "q9_income_mix":{"prompt":"Main income next 3y?",
    "options":{"salary":{"tags":{"income_salary":1},"scenarios":{}},
               "dividends":{"tags":{"income_div":1},"scenarios":{"tech_burst":0.3,"tax_shift":0.3}},
               "rent":{"tags":{"income_rent":1},"scenarios":{"property_crash":0.5,"gilt_selloff":0.3}},
               "pension":{"tags":{"income_pension":1},"scenarios":{}},
               "variable":{"tags":{"income_var":1},"scenarios":{"recession":0.2}}}},
  "q10_ai_effect":{"prompt":"In your field, AI will…",
    "options":{"replace":{"tags":{"tech_conv":-1,"ai_impact":2},"scenarios":{"ai_recession":1.2,"tech_burst":0.4}},
               "augment":{"tags":{"tech_conv":1},"scenarios":{"reflation":0.5}},
               "little":{"tags":{"tech_conv":0},"scenarios":{}}}},
  "q11_drawdown_30_growth":{"prompt":"High-growth fund falls 30%, you…",
    "options":{"add":{"tags":{"contrarian":1,"risk_tol":1},"scenarios":{"tech_burst":-0.3}},
               "hold":{"tags":{"risk_tol":0},"scenarios":{}},
               "reduce":{"tags":{"loss_aversion":1},"scenarios":{"tech_burst":0.3}},
               "exit":{"tags":{"loss_aversion":2},"scenarios":{"tech_burst":0.6}}}},
  "q12_energy_up_20":{"prompt":"Energy bills +20%, you…",
    "options":{"switch":{"tags":{"inflation_sens":1},"scenarios":{"stagflation":0.2}},
               "insulate":{"tags":{"inflation_sens":2},"scenarios":{"stagflation":0.3}},
               "change_travel":{"tags":{"inflation_sens":2},"scenarios":{"energy_spike":0.4}},
               "accept":{"tags":{"inflation_sens":3},"scenarios":{"stagflation":0.4,"energy_spike":0.4}}}},
  "q13_fuel_high_12m":{"prompt":"If fuel stays high 12m, you…",
    "options":{"public_transport":{"tags":{"adapt_speed":1},"scenarios":{"energy_spike":0.2}},
               "switch_ev":{"tags":{"adapt_speed":1},"scenarios":{"energy_spike":0.2}},
               "car_share":{"tags":{"adapt_speed":1},"scenarios":{"energy_spike":0.1}},
               "no_change":{"tags":{"adapt_speed":-1},"scenarios":{"energy_spike":0.3,"stagflation":0.2}}}},
  "q14_overseas_income":{"prompt":"Overseas income/spend next 2y?",
    "options":{"mostly_gbp":{"tags":{"fxv":-1},"scenarios":{}},
               "mixed":{"tags":{"fxv":1},"scenarios":{"devaluation":0.4}},
               "mostly_fx":{"tags":{"fxv":2},"scenarios":{"devaluation":0.8}}}},
  "q15_gbp_drop":{"prompt":"If GBP drops 15%, first you’d…",
    "options":{"shift_global":{"tags":{"fxv":2},"scenarios":{"devaluation":1.2}},
               "increase_gold":{"tags":{"gold_conv":2,"fxv":1},"scenarios":{"devaluation":1.0,"stagflation":0.4}},
               "ignore":{"tags":{"passive_bias":1},"scenarios":{}},
               "rebalance_uk":{"tags":{"home_bias":2},"scenarios":{"tax_shift":0.2}}}},
  "q16_savings_rate_fall":{"prompt":"If savings rates fall from here, you…",
    "options":{"buy_long_gilts":{"tags":{"duration_pref":2},"scenarios":{"reflation":0.8}},
               "move_credit":{"tags":{"credit_pref":2},"scenarios":{"gilt_selloff":0.4}},
               "add_equities":{"tags":{"risk_tol":1},"scenarios":{"reflation":0.5}},
               "leave_cash":{"tags":{"liquidity_pref":1},"scenarios":{"gilt_selloff":0.3}}}},
  "q17_new_isa_dividend":{"prompt":"New ISA for UK dividends appears; you…",
    "options":{"reallocate_yield":{"tags":{"yield_seek":2},"scenarios":{"tax_shift":0.6}},
               "ignore":{"tags":{},"scenarios":{}},
               "diversify_global":{"tags":{"home_bias":-1},"scenarios":{"devaluation":0.2}}}},
  "q18_biggest_regret_5y":{"prompt":"Biggest investing regret 5y?",
    "options":{"didnt_hold":{"tags":{"loss_aversion":-1},"scenarios":{"reflation":0.2}},
               "didnt_take_profits":{"tags":{"momentum_bias":1},"scenarios":{}},
               "too_concentrated":{"tags":{"concern_concentration":2},"scenarios":{"tech_burst":0.2}},
               "too_cautious":{"tags":{"risk_tol":1},"scenarios":{"reflation":0.2}}}},
  "q19_goal_5y":{"prompt":"Primary goal next 5 years?",
    "options":{"preserve":{"tags":{"goal_preserve":2},"scenarios":{"gilt_selloff":0.2}},
               "grow_real":{"tags":{"goal_grow":2},"scenarios":{"reflation":0.3}},
               "max_income":{"tags":{"goal_income":2},"scenarios":{"tax_shift":0.2}},
               "opportunistic":{"tags":{"goal_opportun":2},"scenarios":{"reflation":0.2}}}},
  "q20_turnover":{"prompt":"Portfolio changes per year?",
    "options":{"<1":{"tags":{"turnover_low":1},"scenarios":{}},
               "1_2":{"tags":{},"scenarios":{}},
               "3_4":{"tags":{"turnover_high":1},"scenarios":{"tech_burst":-0.1}},
               ">4":{"tags":{"turnover_high":2},"scenarios":{"tech_burst":-0.2}}}},
  "q21_eis_relief":{"prompt":"30% income tax relief investment (risk higher), you…",
    "options":{"small_slice":{"tags":{"eis_open":1},"scenarios":{"tax_shift":0.4}},
               "pass":{"tags":{"eis_open":-1},"scenarios":{}},
               "core":{"tags":{"eis_open":2},"scenarios":{"tax_shift":0.6}}}},
  "q22_gold_role":{"prompt":"Precious metals are best for…",
    "options":{"insurance":{"tags":{"gold_conv":1},"scenarios":{"stagflation":0.2,"devaluation":0.2}},
               "tactical":{"tags":{"gold_conv":1},"scenarios":{"stagflation":0.1}},
               "core":{"tags":{"gold_conv":2},"scenarios":{"stagflation":0.3,"devaluation":0.3}}}},
  "q23_property_role":{"prompt":"Property in portfolios is primarily for…",
    "options":{"income":{"tags":{"property_income":1},"scenarios":{"property_crash":0.3}},
               "diversification":{"tags":{"property_conf":1},"scenarios":{}},
               "appreciation":{"tags":{"property_conf":2},"scenarios":{}},
               "tax_efficiency":{"tags":{"property_conf":1},"scenarios":{"tax_shift":0.2}}}},
  "q24_windfall_10pct":{"prompt":"A windfall =10% of portfolio; first to…",
    "options":{"debt":{"tags":{"liquidity_pref":1},"scenarios":{"gilt_selloff":0.2}},
               "cash":{"tags":{"liquidity_pref":2},"scenarios":{"recession":0.2}},
               "global_equity":{"tags":{"risk_tol":1},"scenarios":{"reflation":0.3}},
               "gold_commod":{"tags":{"gold_conv":1,"inflation_sens":1},"scenarios":{"stagflation":0.3,"energy_spike":0.3}},
               "alts_eis":{"tags":{"eis_open":2},"scenarios":{"tax_shift":0.4}}}},
  "q25_policy_confidence":{"prompt":"Govt more likely to stabilise or destabilise economy in 5y?",
    "options":{"stabilise":{"tags":{"pci":2},"scenarios":{"reflation":0.6}},
               "neutral":{"tags":{"pci":0},"scenarios":{}},
               "destabilise":{"tags":{"pci":-2},"scenarios":{"gilt_selloff":1.0,"devaluation":0.8,"tax_shift":0.6}}}},
  "q26_recession_cushion":{"prompt":"Confidence in policy cushioning a recession?",
    "options":{"high":{"tags":{"pci":2},"scenarios":{"reflation":0.4}},
               "med":{"tags":{"pci":1},"scenarios":{}},
               "low":{"tags":{"pci":-2},"scenarios":{"recession":0.5,"gilt_selloff":0.4}}}},
  "q27_mobility_future":{"prompt":"Future generations better off than today?",
    "options":{"yes":{"tags":{"macro_optimism":1},"scenarios":{"reflation":0.2}},
               "unsure":{"tags":{},"scenarios":{}},
               "no":{"tags":{"macro_pessimism":1},"scenarios":{"property_crash":0.2,"recession":0.2}}}},
  "q28_local_invest_vs_property":{"prompt":"Local businesses/infrastructure vs real estate attractiveness?",
    "options":{"prefer_local":{"tags":{"property_caution":1},"scenarios":{"property_crash":0.2}},
               "equal":{"tags":{},"scenarios":{}},
               "prefer_property":{"tags":{"property_conf":1},"scenarios":{}}}}
}
